id = "hlsl"
name = "HLSL"
version = "0.0.2"
schema_version = 1
authors = ["shiruba"]
description = "HLSL language support."
repository = "https://github.com/XavierCS-dev/zed-hlsl"

[grammars.hlsl]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-hlsl"
commit = "80517ca13317fb8591503c0d99f2ad76e8979a72"
